Update on Tue Jul 29 13:58:55 UTC 2025

diff --git a/docker/repos/alpaquita-linux-base/Dockerfile b/docker/repos/alpaquita-linux-base/Dockerfile
--- a/docker/repos/alpaquita-linux-base/Dockerfile
+++ b/docker/repos/alpaquita-linux-base/Dockerfile
@@ -12,6 +12,8 @@ ARG APK_REPOS=""
 # Space-separated list of locales to install in addition to those
 # which come in the minirootfs. For example, "fr_FR.UTF-8 zh_CN.utf8"
 ARG LOCALES=""
+# Whether to remove APK tools from the image
+ARG REMOVE_APK_TOOLS="no"
 
 ARG MAINTAINER=""
 ARG DESCRIPTION=""
@@ -38,6 +40,14 @@ RUN \
             exit 1; \
             ;; \
     esac; \
+    case "$REMOVE_APK_TOOLS" in \
+        yes|no) ;; \
+        *) \
+            echo "Invalid REMOVE_APK_TOOLS: '${REMOVE_APK_TOOLS}'. "; \
+            echo "Only 'yes' and 'no' are supported."; \
+            exit 1; \
+            ;; \
+    esac; \
     if [ -n "$APK_REPOS" ]; then \
         printf '%s\n' $APK_REPOS | tee /etc/apk/repositories; \
     fi; \
@@ -51,6 +61,9 @@ RUN \
        locale-gen --no-archive $LOCALES; \
        apk del --no-cache glibc-locales ; \
        rm -f /etc/locale.gen; \
+    fi; \
+    if [ "$REMOVE_APK_TOOLS" = "yes" ]; then \
+        apk del --no-cache apk-tools; \
     fi
 
 CMD ["/bin/sh"]
diff --git a/docker/repos/alpaquita-linux-go/Dockerfile b/docker/repos/alpaquita-linux-go/Dockerfile
--- a/docker/repos/alpaquita-linux-go/Dockerfile
+++ b/docker/repos/alpaquita-linux-go/Dockerfile
@@ -5,6 +5,9 @@
 ARG BASE_IMAGE="bellsoft/alpaquita-linux-base:stream-musl"
 FROM "$BASE_IMAGE"
 
+# Whether to remove APK tools from the image
+ARG REMOVE_APK_TOOLS="no"
+
 ARG MAINTAINER=""
 ARG DESCRIPTION=""
 
@@ -14,6 +17,14 @@ LABEL org.opencontainers.image.description="$DESCRIPTION"
 
 RUN \
     set -e; command set -o pipefail; \
+    case "$REMOVE_APK_TOOLS" in \
+        yes|no) ;; \
+        *) \
+            echo "Invalid REMOVE_APK_TOOLS: '${REMOVE_APK_TOOLS}'. "; \
+            echo "Only 'yes' and 'no' are supported."; \
+            exit 1; \
+            ;; \
+    esac; \
     apk add --no-cache \
         bash \
         binutils \
@@ -21,12 +32,14 @@ RUN \
         findutils \
         g++ \
         gcc \
-        git \
         go \
         go-doc \
         libc-dev \
         make \
-        openssh-client
+        openssh-client; \
+    if [ "$REMOVE_APK_TOOLS" = "yes" ]; then \
+        apk del --no-cache apk-tools; \
+    fi
 
 # See https://tip.golang.org/doc/go1.20#minor_library_changes
 ENV GODEBUG="tarinsecurepath=0,zipinsecurepath=0"
diff --git a/docker/repos/alpaquita-linux-python/Dockerfile b/docker/repos/alpaquita-linux-python/Dockerfile
--- a/docker/repos/alpaquita-linux-python/Dockerfile
+++ b/docker/repos/alpaquita-linux-python/Dockerfile
@@ -5,6 +5,9 @@
 ARG BASE_IMAGE="bellsoft/alpaquita-linux-base:stream-musl"
 FROM "$BASE_IMAGE"
 
+# Whether to remove APK tools from the image
+ARG REMOVE_APK_TOOLS="no"
+
 ARG MAINTAINER=""
 ARG DESCRIPTION=""
 
@@ -14,4 +17,15 @@ LABEL org.opencontainers.image.description="$DESCRIPTION"
 
 RUN \
     set -e; command set -o pipefail; \
-    apk add --no-cache python3 py3-pip py3-wheel py3-setuptools
+    case "$REMOVE_APK_TOOLS" in \
+        yes|no) ;; \
+        *) \
+            echo "Invalid REMOVE_APK_TOOLS: '${REMOVE_APK_TOOLS}'. "; \
+            echo "Only 'yes' and 'no' are supported."; \
+            exit 1; \
+            ;; \
+    esac; \
+    apk add --no-cache python3 py3-pip py3-wheel py3-setuptools; \
+    if [ "$REMOVE_APK_TOOLS" = "yes" ]; then \
+        apk del --no-cache apk-tools; \
+    fi
diff --git a/docker/repos/liberica-native-image-kit-container/Dockerfile b/docker/repos/liberica-native-image-kit-container/Dockerfile
--- a/docker/repos/liberica-native-image-kit-container/Dockerfile
+++ b/docker/repos/liberica-native-image-kit-container/Dockerfile
@@ -9,9 +9,10 @@ FROM "$BASE_IMAGE"
 ARG NIK_RELEASE="24"
 # 11, 17, 21, 22, 23, 24 are supported
 ARG JAVA_RELEASE="24"
-
 # Debug image includes additional components for debugging
 ARG IS_DEBUG_IMAGE="no"
+# Whether to remove APK tools from the image
+ARG REMOVE_APK_TOOLS="no"
 
 ARG MAINTAINER=""
 ARG DESCRIPTION=""
@@ -39,7 +40,18 @@ RUN \
             exit 1; \
             ;; \
     esac; \
+    case "$REMOVE_APK_TOOLS" in \
+        yes|no) ;; \
+        *) \
+            echo "Invalid REMOVE_APK_TOOLS: '${REMOVE_APK_TOOLS}'. "; \
+            echo "Only 'yes' and 'no' are supported."; \
+            exit 1; \
+            ;; \
+    esac; \
     apk add --no-cache "liberica-nik-${NIK_RELEASE}-${JAVA_RELEASE}"; \
     if [ "$IS_DEBUG_IMAGE" = "yes" ]; then \
         apk add --no-cache maven gdb; \
+    fi; \
+    if [ "$REMOVE_APK_TOOLS" = "yes" ]; then \
+        apk del --no-cache apk-tools; \
     fi
